backend:
  name: github
  repo: mkacem/headless-cms
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img

collections:
  - name: layout/home
    label: layout/home
    label_singular: layout/home
    folder: content/layout/home
    create: true
    fields: [
      {name: title, label: Title, widget: string},
      {name: body, label: Body, widget: markdown},
    ]
  - name: layout/testimonials
    label: layout/testimonials
    label_singular: layout/testimonials
    folder: content/layout/testimonials
    create: true
    fields: [
      {name: title, label: Title, widget: string},
      {name: body, label: Body, widget: markdown},
      {name: body2, label: Body2, widget: markdown},
    ]
  - name: 'menus'
    label: 'Menus'
    folder: 'content/menus'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false

    
    fields:
      - { label: 'title', name: 'title', widget: 'string' }
      - label: "Section Menu"
        name: "section_menu"
        widget: "list"
        fields:
          - label: "Label"
            name: "label"
            widget: "string"
            hint: "The label for the menu item (e.g., 'About Us')"
          - label: "Label Fr"
            name: "label_fr"
            widget: "string"
            hint: "The French label for the menu item (e.g., 'À propos de nous')"
          - label: "Path"
            name: "path"
            widget: "string" # Using the number widget ensures numerical data
            hint: "The URL path for the menu item (e.g., '/about')"
            required: false
          - label: "Section Menu"
            name: "section_menu"
            widget: "list"
            summary: "{{label}} ({{value}})" # A helpful summary for collapsed list items
            fields:
              - label: "Label"
                name: "label"
                widget: "string"
                hint: "The label for the menu item (e.g., 'About Us')"
              - label: "Label Fr"
                name: "label_fr"
                widget: "string"
                hint: "The French label for the menu item (e.g., 'À propos de nous')"
              - { label: 'position', name: 'position', widget: 'select', options: ["left", "center", "right"] }
              - label: "Section Menu Items"
                name: "section_menu_items"
                widget: "list"
                summary: "{{label}} ({{value}})" # A helpful summary for collapsed list items
                fields:
                  - label: "Label"
                    name: "label"
                    widget: "string"
                  - label: "Label Fr"
                    name: "label_fr"
                    widget: "string"
                  - label: 'Description'
                    name: 'menu_description'
                    widget: 'string' 
                    required: false
                  - label: 'Description FR'
                    name: 'menu_description_fr'
                    widget: 'string' 
                    required: false
                  - label: 'Body'
                    name: 'menu_body'
                    widget: 'markdown' 
                    required: false
                  - label: 'Body Fr'
                    name: 'menu_body_fr'
                    widget: 'markdown' 
                    required: false
                  - label: 'Featured Image'
                    name: 'menu_featured_image'
                    widget: 'image' 
                    required: false
                  - label: "Path"
                    name: "path"
                    widget: "string" # Using the number widget ensures numerical data
                    hint: "The URL path for the menu item (e.g., '/about')"
                    required: false
      - label: "Menu Items"
        name: "menu_items"
        widget: "list"
        summary: "{{label}} ({{value}})" # A helpful summary for collapsed list items
        fields:
          - label: "Label"
            name: "label"
            widget: "string"
            hint: "The label for the menu item (e.g., 'About Us')"
          - label: "Label Fr"
            name: "label_fr"
            widget: "string"
            hint: "The French label for the menu item (e.g., 'À propos de nous')"
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Description FR', name: 'description_fr', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Body Fr', name: 'body_fr', widget: 'markdown' }
          - { label: 'Featured Image', name: 'featured_image', widget: 'image' }
          - label: "Path"
            name: "path"
            widget: "string" # Using the number widget ensures numerical data
            hint: "The URL path for the menu item (e.g., '/about')"
            
  - name: en
    label: en
    label_singular: En
    folder: content/en
    create: true
    fields: [
      {name: title, label: Title, widget: string},
      {name: body, label: Body, widget: markdown},
    ]
    # Add nested and meta objects
    nested:
      depth: 100
      summary: '{{title}}'
      subfolders: true
    meta: { path: { widget: string, label: 'Path', index_file: 'index', visible: true } }
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    fields: [
      {name: title, label: Title, widget: string},
      {name: body, label: Body, widget: markdown},
    ]
    # Add nested and meta objects
    nested:
      depth: 100
      summary: '{{title}}'
      subfolders: true
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title Fr', name: 'title_fr', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Description FR', name: 'description_fr', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Body Fr', name: 'body_fr', widget: 'markdown' }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image' }
      - label: "Testimonials"
        name: "testimonials"
        minimize_collapsed: true
        widget: "list"
        fields:
          - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
          - {label: Author, name: author, widget: string }
      - label: "Data Points"
        name: "data_points"
        widget: "list"
        summary: "{{label}} ({{value}})" # A helpful summary for collapsed list items
        fields:
          - label: "Label"
            name: "label"
            widget: "string"
            hint: "The label for the x-axis (e.g., 'January')"
          - label: "Value"
            name: "value"
            widget: "string" # Using the number widget ensures numerical data
            hint: "The numerical value for the chart"
          - label: "Color"
            name: "color"
            widget: "color" # Optional: add a color picker for customization