backend:
  name: github
  repo: mkacem/headless-cms
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    fields: [
      {name: title, label: Title, widget: string},
      {name: body, label: Body, widget: markdown},
    ]
    # Add nested and meta objects
    nested:
      depth: 100
      summary: '{{title}}'
      subfolders: true
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Data Points"
        name: "data_points"
        widget: "list"
        summary: "{{label}} ({{value}})" # A helpful summary for collapsed list items
        fields:
          - label: "Label"
            name: "label"
            widget: "string"
            hint: "The label for the x-axis (e.g., 'January')"
          - label: "Value"
            name: "value"
            widget: "string" # Using the number widget ensures numerical data
            hint: "The numerical value for the chart"
          - label: "Color"
            name: "color"
            widget: "color" # Optional: add a color picker for customization